// Mock data for the application

export const mockHotels = [
  {
    id: 1,
    name: "Grand Bay Resort",
    rooms: 320,
    plan: "Tier 4",
    status: "live",
    mrr: 4125,
    country: "UK",
    setupFee: 5000,
    setupFeePaid: true,
    features: {
      roomServiceAI: true,
      voiceOrdering: true,
      upsellEngine: true,
    },
    language: "English",
    timezone: "Europe/London",
  },
  {
    id: 2,
    name: "The Majestic London",
    rooms: 180,
    plan: "Tier 3",
    status: "live",
    mrr: 2458,
    country: "UK",
    setupFee: 3500,
    setupFeePaid: true,
    features: {
      roomServiceAI: true,
      voiceOrdering: true,
      upsellEngine: true,
    },
    language: "English",
    timezone: "Europe/London",
  },
  {
    id: 3,
    name: "Cornwall Luxury Hotel",
    rooms: 85,
    plan: "Tier 2",
    status: "trial",
    mrr: 1792,
    country: "UK",
    setupFee: 2500,
    setupFeePaid: false,
    features: {
      roomServiceAI: true,
      voiceOrdering: false,
      upsellEngine: true,
    },
    language: "English",
    timezone: "Europe/London",
  },
  {
    id: 4,
    name: "The Riviera Suites",
    rooms: 45,
    plan: "Tier 1",
    status: "live",
    mrr: 1208,
    country: "France",
    setupFee: 2000,
    setupFeePaid: true,
    features: {
      roomServiceAI: true,
      voiceOrdering: false,
      upsellEngine: true,
    },
    language: "French",
    timezone: "Europe/Paris",
  },
  {
    id: 5,
    name: "Manhattan Grand Hotel",
    rooms: 480,
    plan: "Tier 5",
    status: "live",
    mrr: 5792,
    country: "USA",
    setupFee: 7500,
    setupFeePaid: true,
    features: {
      roomServiceAI: true,
      voiceOrdering: true,
      upsellEngine: true,
    },
    language: "English",
    timezone: "America/New_York",
  },
  {
    id: 6,
    name: "Dubai Palace Resort",
    rooms: 650,
    plan: "Tier 5",
    status: "live",
    mrr: 5792,
    country: "UAE",
    setupFee: 10000,
    setupFeePaid: true,
    features: {
      roomServiceAI: true,
      voiceOrdering: true,
      upsellEngine: true,
    },
    language: "English",
    timezone: "Asia/Dubai",
  },
  {
    id: 7,
    name: "Tuscany Villa Collection",
    rooms: 35,
    plan: "Tier 1",
    status: "past_due",
    mrr: 1208,
    country: "Italy",
    setupFee: 2000,
    setupFeePaid: true,
    features: {
      roomServiceAI: true,
      voiceOrdering: false,
      upsellEngine: false,
    },
    language: "Italian",
    timezone: "Europe/Rome",
  },
  {
    id: 8,
    name: "Tokyo Luxury Suites",
    rooms: 220,
    plan: "Tier 3",
    status: "live",
    mrr: 2458,
    country: "Japan",
    setupFee: 4000,
    setupFeePaid: true,
    features: {
      roomServiceAI: true,
      voiceOrdering: true,
      upsellEngine: true,
    },
    language: "Japanese",
    timezone: "Asia/Tokyo",
  },
];

export const mockOrders = [
  {
    id: 2048,
    room: 412,
    items: ["Cheeseburger", "Fries", "Coke"],
    status: "in_progress",
    channel: "voice",
    time: "12:02",
    date: "2026-01-23",
    total: 28.50,
    upsell: "Added Coke",
    specialRequests: "No pickles",
  },
  {
    id: 2047,
    room: 305,
    items: ["Caesar Salad", "Grilled Salmon", "White Wine"],
    status: "ready",
    channel: "chat",
    time: "11:45",
    date: "2026-01-23",
    total: 52.00,
    upsell: "Added White Wine",
    specialRequests: "Dressing on the side",
  },
  {
    id: 2046,
    room: 108,
    items: ["Continental Breakfast", "Orange Juice", "Coffee"],
    status: "delivered",
    channel: "voice",
    time: "08:15",
    date: "2026-01-23",
    total: 22.00,
    upsell: null,
    specialRequests: null,
  },
  {
    id: 2045,
    room: 521,
    items: ["Club Sandwich", "Side Salad", "Iced Tea"],
    status: "new",
    channel: "chat",
    time: "12:18",
    date: "2026-01-23",
    total: 35.50,
    upsell: "Added Iced Tea",
    specialRequests: "Gluten-free bread",
  },
  {
    id: 2044,
    room: 203,
    items: ["Steak Frites", "Red Wine", "Chocolate Mousse"],
    status: "delivered",
    channel: "voice",
    time: "19:30",
    date: "2026-01-22",
    total: 78.00,
    upsell: "Added Chocolate Mousse",
    specialRequests: "Medium rare",
  },
];

export const mockMenuItems = [
  { id: 1, name: "Cheeseburger", category: "Mains", price: 18.50, available: true, upsellEnabled: true },
  { id: 2, name: "Club Sandwich", category: "Mains", price: 16.00, available: true, upsellEnabled: true },
  { id: 3, name: "Grilled Salmon", category: "Mains", price: 32.00, available: true, upsellEnabled: true },
  { id: 4, name: "Caesar Salad", category: "Starters", price: 12.00, available: true, upsellEnabled: false },
  { id: 5, name: "French Onion Soup", category: "Starters", price: 10.00, available: true, upsellEnabled: false },
  { id: 6, name: "Chocolate Mousse", category: "Desserts", price: 9.00, available: true, upsellEnabled: true },
  { id: 7, name: "Tiramisu", category: "Desserts", price: 11.00, available: false, upsellEnabled: true },
  { id: 8, name: "Red Wine (Glass)", category: "Drinks", price: 12.00, available: true, upsellEnabled: true },
  { id: 9, name: "White Wine (Glass)", category: "Drinks", price: 12.00, available: true, upsellEnabled: true },
  { id: 10, name: "Coca-Cola", category: "Drinks", price: 4.50, available: true, upsellEnabled: true },
];

export const mockRooms = [
  { number: 101, qrActive: true, lastOrder: "2026-01-23 08:15" },
  { number: 102, qrActive: true, lastOrder: null },
  { number: 103, qrActive: true, lastOrder: "2026-01-22 20:30" },
  { number: 104, qrActive: false, lastOrder: null },
  { number: 105, qrActive: true, lastOrder: "2026-01-23 12:05" },
  { number: 201, qrActive: true, lastOrder: "2026-01-22 19:00" },
  { number: 202, qrActive: true, lastOrder: null },
  { number: 203, qrActive: true, lastOrder: "2026-01-22 19:30" },
  { number: 301, qrActive: true, lastOrder: "2026-01-23 10:45" },
  { number: 305, qrActive: true, lastOrder: "2026-01-23 11:45" },
];

export const mockStaff = [
  { id: 1, name: "James Wilson", role: "General Manager", accessLevel: "Full Access", status: "Active" },
  { id: 2, name: "Sarah Chen", role: "F&B Manager", accessLevel: "Menu & Orders", status: "Active" },
  { id: 3, name: "Michael Brown", role: "Night Manager", accessLevel: "Orders Only", status: "Active" },
  { id: 4, name: "Emma Davis", role: "Assistant Manager", accessLevel: "Menu & Reports", status: "Active" },
  { id: 5, name: "David Miller", role: "Supervisor", accessLevel: "Orders Only", status: "Inactive" },
];

export const mockCRMLeads = [
  {
    id: 1,
    hotelName: "The Dorchester",
    contactName: "John Smith",
    role: "General Manager",
    phone: "+44 20 7629 8888",
    mobile: "+44 7700 900123",
    email: "j.smith@thedorchester.com",
    city: "London",
    country: "United Kingdom",
    timezone: "Europe/London",
    status: "lead",
    value: 45000,
    nextActionDate: "2026-01-25",
    lastActivity: "Lead created · 3 days ago",
    activities: [
      { id: 1, type: "lead_created", timestamp: "2026-01-20T10:30:00Z", user: "Sarah Mitchell", note: "Inbound from website" },
    ],
    notes: [],
  },
  {
    id: 2,
    hotelName: "Claridge's",
    contactName: "Emma Thompson",
    role: "Director of Operations",
    phone: "+44 20 7107 8888",
    mobile: "+44 7700 900456",
    email: "e.thompson@claridges.co.uk",
    city: "London",
    country: "United Kingdom",
    timezone: "Europe/London",
    status: "contacted",
    value: 52000,
    nextActionDate: "2026-01-24",
    lastActivity: "SMS sent · 1 day ago",
    activities: [
      { id: 1, type: "lead_created", timestamp: "2026-01-18T09:00:00Z", user: "Tom Harrison", note: null },
      { id: 2, type: "sms_sent", timestamp: "2026-01-22T14:30:00Z", user: "Tom Harrison", note: "Intro follow-up message sent" },
    ],
    notes: [
      { id: 1, text: "Very interested in AI voice ordering", timestamp: "2026-01-19T11:00:00Z", user: "Tom Harrison" },
    ],
  },
  {
    id: 3,
    hotelName: "The Savoy",
    contactName: "Michael Roberts",
    role: "F&B Director",
    phone: "+44 20 7836 4343",
    mobile: "+44 7700 900789",
    email: "m.roberts@thesavoy.co.uk",
    city: "London",
    country: "United Kingdom",
    timezone: "Europe/London",
    status: "demo",
    value: 58000,
    nextActionDate: "2026-01-26",
    lastActivity: "Demo scheduled · Today",
    activities: [
      { id: 1, type: "lead_created", timestamp: "2026-01-15T10:00:00Z", user: "Lisa Wang", note: null },
      { id: 2, type: "call_made", timestamp: "2026-01-17T15:30:00Z", user: "Lisa Wang", note: "Spoke with decision maker, very positive", duration: 720 },
      { id: 3, type: "demo_scheduled", timestamp: "2026-01-23T09:00:00Z", user: "Lisa Wang", note: "Demo set for Jan 26 at 2pm GMT" },
    ],
    notes: [
      { id: 1, text: "Currently using manual room service system", timestamp: "2026-01-17T16:00:00Z", user: "Lisa Wang" },
      { id: 2, text: "Interested in Simphony integration", timestamp: "2026-01-17T16:05:00Z", user: "Lisa Wang" },
    ],
  },
  {
    id: 4,
    hotelName: "The Ritz Paris",
    contactName: "Marie Dubois",
    role: "Directrice Générale",
    phone: "+33 1 43 16 30 30",
    mobile: "+33 6 12 34 56 78",
    email: "m.dubois@ritzparis.com",
    city: "Paris",
    country: "France",
    timezone: "Europe/Paris",
    status: "proposal",
    value: 62000,
    nextActionDate: "2026-01-25",
    lastActivity: "Proposal sent · 2 days ago",
    activities: [
      { id: 1, type: "lead_created", timestamp: "2026-01-10T14:00:00Z", user: "Sarah Mitchell", note: null },
      { id: 2, type: "email_sent", timestamp: "2026-01-12T10:00:00Z", user: "Sarah Mitchell", note: "Initial intro email" },
      { id: 3, type: "call_made", timestamp: "2026-01-14T11:30:00Z", user: "Sarah Mitchell", note: "Discovery call completed", duration: 1800 },
      { id: 4, type: "demo_completed", timestamp: "2026-01-18T15:00:00Z", user: "Sarah Mitchell", note: "Full product demo, very engaged" },
      { id: 5, type: "proposal_sent", timestamp: "2026-01-21T09:00:00Z", user: "Sarah Mitchell", note: "Custom proposal for 150 rooms" },
    ],
    notes: [
      { id: 1, text: "Luxury property, high standards", timestamp: "2026-01-14T12:00:00Z", user: "Sarah Mitchell" },
      { id: 2, text: "Need French language support", timestamp: "2026-01-14T12:05:00Z", user: "Sarah Mitchell" },
      { id: 3, text: "Budget approved, waiting on legal review", timestamp: "2026-01-21T09:30:00Z", user: "Sarah Mitchell" },
    ],
  },
  {
    id: 5,
    hotelName: "Four Seasons NYC",
    contactName: "David Johnson",
    role: "VP of Food & Beverage",
    phone: "+1 212 758 5700",
    mobile: "+1 917 555 0199",
    email: "d.johnson@fourseasons.com",
    city: "New York",
    country: "United States",
    timezone: "America/New_York",
    status: "won",
    value: 75000,
    nextActionDate: null,
    lastActivity: "Deal won · 5 days ago",
    activities: [
      { id: 1, type: "lead_created", timestamp: "2025-12-15T10:00:00Z", user: "Tom Harrison", note: null },
      { id: 2, type: "call_made", timestamp: "2025-12-18T14:00:00Z", user: "Tom Harrison", note: "Initial discovery call", duration: 900 },
      { id: 3, type: "demo_scheduled", timestamp: "2025-12-20T10:00:00Z", user: "Tom Harrison", note: null },
      { id: 4, type: "demo_completed", timestamp: "2026-01-05T16:00:00Z", user: "Tom Harrison", note: "Demo went excellent" },
      { id: 5, type: "proposal_sent", timestamp: "2026-01-08T09:00:00Z", user: "Tom Harrison", note: "Enterprise tier proposal" },
      { id: 6, type: "stage_changed", timestamp: "2026-01-18T11:00:00Z", user: "Tom Harrison", note: "Contract signed!", fromStage: "proposal", toStage: "won" },
    ],
    notes: [
      { id: 1, text: "Decision maker, very technical", timestamp: "2025-12-18T14:30:00Z", user: "Tom Harrison" },
      { id: 2, text: "Wants multi-language support (English, Spanish, French)", timestamp: "2026-01-05T16:30:00Z", user: "Tom Harrison" },
      { id: 3, text: "Contract value: $75k setup + $5.2k MRR", timestamp: "2026-01-18T11:15:00Z", user: "Tom Harrison" },
    ],
  },
  {
    id: 6,
    hotelName: "Peninsula Beverly Hills",
    contactName: "Lisa Anderson",
    role: "General Manager",
    phone: "+1 310 551 2888",
    mobile: "+1 310 555 0177",
    email: "l.anderson@peninsula.com",
    city: "Beverly Hills",
    country: "United States",
    timezone: "America/Los_Angeles",
    status: "lost",
    value: 48000,
    nextActionDate: null,
    lastActivity: "Lost · 8 days ago",
    activities: [
      { id: 1, type: "lead_created", timestamp: "2025-12-20T10:00:00Z", user: "Lisa Wang", note: null },
      { id: 2, type: "email_sent", timestamp: "2025-12-22T09:00:00Z", user: "Lisa Wang", note: "Initial outreach" },
      { id: 3, type: "call_made", timestamp: "2026-01-05T11:00:00Z", user: "Lisa Wang", note: "Discovery call", duration: 600 },
      { id: 4, type: "stage_changed", timestamp: "2026-01-15T14:00:00Z", user: "Lisa Wang", note: "Went with competitor", fromStage: "contacted", toStage: "lost", lostReason: "Price" },
    ],
    notes: [
      { id: 1, text: "Price sensitive, comparing multiple vendors", timestamp: "2026-01-05T11:30:00Z", user: "Lisa Wang" },
      { id: 2, text: "Lost to competitor - lower pricing", timestamp: "2026-01-15T14:05:00Z", user: "Lisa Wang" },
    ],
  },
];

export const mockInvoices = [
  { id: 1, hotel: "Grand Bay Resort", amount: 4125, status: "paid", date: "2026-01-01", dueDate: "2026-01-15" },
  { id: 2, hotel: "The Majestic London", amount: 2458, status: "paid", date: "2026-01-01", dueDate: "2026-01-15" },
  { id: 3, hotel: "Tuscany Villa Collection", amount: 1208, status: "overdue", date: "2025-12-01", dueDate: "2025-12-15" },
  { id: 4, hotel: "Manhattan Grand Hotel", amount: 5792, status: "paid", date: "2026-01-01", dueDate: "2026-01-15" },
];

export const mockSalesReps = [
  { id: 1, name: "Sarah Mitchell", dealsWon: 8, setupFees: 42000, monthlyResiduals: 18500 },
  { id: 2, name: "Tom Harrison", dealsWon: 5, setupFees: 28000, monthlyResiduals: 12000 },
  { id: 3, name: "Lisa Wang", dealsWon: 12, setupFees: 68000, monthlyResiduals: 32000 },
];

export const mockSupportTickets = [
  { id: 1, hotel: "Grand Bay Resort", issue: "Voice ordering not responding", priority: "high", status: "open", created: "2026-01-23 10:30" },
  { id: 2, hotel: "Cornwall Luxury Hotel", issue: "Menu sync issue", priority: "medium", status: "in_progress", created: "2026-01-22 14:20" },
  { id: 3, hotel: "The Majestic London", issue: "QR codes not generating", priority: "low", status: "resolved", created: "2026-01-21 09:15" },
];

export const mockBlogPosts = [
  {
    id: 1,
    title: 'How AI is Transforming Hotel Room Service',
    excerpt: 'Discover how artificial intelligence is revolutionizing the guest experience and increasing revenue for hotels worldwide.',
    content: 'Full blog content here...',
    author: 'Sarah Mitchell',
    date: '2026-01-20',
    readTime: '5 min read',
    category: 'Technology',
    image: '/blog/ai-hotel.jpg',
    slug: 'ai-transforming-hotel-room-service',
    published: true,
  },
  {
    id: 2,
    title: '10 Ways to Reduce Room Service Order Errors',
    excerpt: 'Learn practical strategies to minimize mistakes and improve guest satisfaction with your room service operations.',
    content: 'Full blog content here...',
    author: 'James Chen',
    date: '2026-01-15',
    readTime: '7 min read',
    category: 'Best Practices',
    image: '/blog/reduce-errors.jpg',
    slug: 'reduce-room-service-errors',
    published: true,
  },
  {
    id: 3,
    title: 'The ROI of Voice AI for Hotels',
    excerpt: 'A comprehensive analysis of how voice AI technology delivers measurable returns for hotel properties.',
    content: 'Full blog content here...',
    author: 'Emma Thompson',
    date: '2026-01-10',
    readTime: '6 min read',
    category: 'Business',
    image: '/blog/roi-voice-ai.jpg',
    slug: 'roi-voice-ai-hotels',
    published: true,
  },
  {
    id: 4,
    title: 'Guest Experience Trends in 2026',
    excerpt: 'Stay ahead of the curve with the latest trends shaping guest expectations in luxury hospitality.',
    content: 'Full blog content here...',
    author: 'Michael Rodriguez',
    date: '2026-01-05',
    readTime: '8 min read',
    category: 'Industry Trends',
    image: '/blog/guest-trends.jpg',
    slug: 'guest-experience-trends-2026',
    published: true,
  },
  {
    id: 5,
    title: 'Implementing AI: A Step-by-Step Guide',
    excerpt: 'Everything you need to know about implementing AI technology in your hotel operations.',
    content: 'Full blog content here...',
    author: 'Sarah Mitchell',
    date: '2025-12-28',
    readTime: '10 min read',
    category: 'Implementation',
    image: '/blog/implementation-guide.jpg',
    slug: 'implementing-ai-guide',
    published: true,
  },
  {
    id: 6,
    title: 'Success Story: How The Dorchester Increased Revenue by 35%',
    excerpt: 'Learn how one of London\'s most prestigious hotels leveraged AI to dramatically improve their room service operations.',
    content: 'Full blog content here...',
    author: 'James Chen',
    date: '2025-12-20',
    readTime: '6 min read',
    category: 'Case Studies',
    image: '/blog/dorchester-success.jpg',
    slug: 'dorchester-success-story',
    published: true,
  },
];
